# Generated by Django 5.1.4 on 2024-12-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_name',
        ),
    ]
