# Generated by Django 5.1.4 on 2024-12-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0002_rename_product_order_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
