# Generated by Django 5.1.4 on 2024-12-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0004_remove_order_total_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
    ]
