# Generated by Django 5.1.4 on 2025-01-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0009_rename_status_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
