# Generated by Django 5.1.4 on 2025-01-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0010_product_quantity_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
