# Generated by Django 5.1.4 on 2025-01-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0011_order_is_valid_product_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_valid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_valid',
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
