# Generated by Django 5.1.4 on 2025-01-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0012_remove_order_is_valid_remove_product_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
