# Generated by Django 5.1.4 on 2025-01-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0014_alter_order_quantity_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
