# Generated by Django 5.1.4 on 2025-01-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0015_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
