# Generated by Django 5.1.4 on 2025-01-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0016_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
    ]
