# Generated by Django 5.1.4 on 2025-01-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0017_product_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
