# Generated by Django 5.1.4 on 2025-01-01 09:59

import midtrans.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0018_remove_order_order_id_remove_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=midtrans.utils.random_string_generator, max_length=255),
        ),
    ]
