# Generated by Django 5.1.4 on 2025-01-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0019_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
