# Generated by Django 5.1.4 on 2025-01-02 08:28

import datetime
import midtrans.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0020_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('order_id', models.CharField(default=midtrans.utils.random_order_id, max_length=255)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=midtrans.utils.random_order_id, max_length=255),
        ),
    ]
