# Generated by Django 5.1.4 on 2025-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0021_checkoutdata_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdata',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdata',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdata',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdata',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdata',
            name='zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
