# Generated by Django 5.1.4 on 2025-01-09 09:39

import midtrans.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midtrans', '0022_alter_checkoutdata_address_alter_checkoutdata_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=midtrans.utils.random_order_id, max_length=255, unique=True),
        ),
    ]
